### ISSUE TITLE
Práctica Diagrama de Clases - Edwin López Santiago

### ISSUE THREAD

**Issue by Edwin14459** [SistemasTecTlaxiaco/actividad-3-practica-architect-Edwin14459#1]
[Práctica Diagrama de Clases - Edwin López Santiago.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-Edwin14459/files/12561861/Practica.Diagrama.de.Clases.-.Edwin.Lopez.Santiago.pdf)

**Comment by Luz1727** [comment]
calificacion 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
